version: "3.8"
services:
  server:
    environment:
      - MYSQL_URL:mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: campuslib
      MYSQL_USER: letmein
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: root